run:
  timeout: 3m
  go: "1.24"
  modules-download-mode: readonly
  skip-dirs:
    - build
    - dist

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - gofmt
    - goimports
    - misspell
    - gosec
  disable:
    - godot

linters-settings:
  goimports:
    local-prefixes: craftops
  misspell:
    locale: US
  errcheck:
    check-type-assertions: false
    check-blank: false
  gosec:
    severity: medium
    excludes:
      - G104  # Duplicate with errcheck

issues:
  exclude-rules:
    # Tests: relax security and errcheck noise
    - path: _test\.go
      linters: [gosec, errcheck]
    # CLI entrypoint often prints and ignores errors intentionally
    - path: cmd/
      linters: [errcheck]
    # Common safe patterns
    - text: "Error return value of.*Print.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Write.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Close.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Remove.*is not checked"
      linters: [errcheck]

severity:
  default-severity: error
