version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
  disable:
    - godot
    - gosec

issues:
  exclude-dirs:
    - build
    - dist
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
    - path: ^cmd/
      linters: [errcheck]
    - path: ^internal/ui/
      linters: [errcheck]
    - text: "Error return value of.*Close.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Remove.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Fprint.*is not checked"
      linters: [errcheck]
