# .golangci.yml configuration
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  # version is required by some schema validators
  version: "1"
  timeout: 5m
  modules-download-mode: readonly

linters:
  # enable-all: false is preferred by some validators over disable-all: true
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - revive
    - bodyclose
    - unconvert
    - goconst

issues:
  # exclude-use-default was replaced by exclude-rules in some schemas, 
  # but here we keep it explicit and compliant.
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
