version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosec
  disable:
    - godot

issues:
  exclude-dirs:
    - build
    - dist
  exclude-rules:
    - path: _test\.go
      linters: [gosec, errcheck]
    - path: ^cmd/
      linters: [errcheck]
