version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - revive
    - bodyclose
    - unconvert
    - goconst

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
