version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Automatically rebase PRs when conflicts occur
    rebase-strategy: "auto"
    # Limit the number of open PRs at any time
    open-pull-requests-limit: 5
    # Group patch updates together to reduce noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Add prefix to PR titles for easy identification
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Add custom labels to Dependabot PRs
    labels:
      - "dependencies"
      - "automated"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
