[kodiak]
version = 1

[kodiak.merge]
method = "squash"
delete_branch_on_merge = true
require_automerge_label = false
blocking_labels = ["needs-review", "do-not-merge", "wip", "work-in-progress"]
automerge_label = "auto-merge"
priority_merge_label = "urgent"
max_commit_message_body_length = 5000

[kodiak.merge.message]
title = "pull_request_title"
body = "pull_request_body"
strip_html_comments = true

[kodiak.update]
always = true

[kodiak.approve]
auto_approve_usernames = ["renovate[bot]", "dependabot[bot]", "github-actions[bot]"]
auto_approve_labels = ["dependencies", "auto-merge"]
block_auto_approve_labels = ["needs-review", "major-update"]

[kodiak.checks]
# Required checks to merge
required_statuses = [
  "Test & Lint",
  "Build (linux, amd64)",
  "Build (linux, arm64)",
  "Build (darwin, amd64)",
  "Build (darwin, arm64)"
]

optional_statuses = ["Security Analysis"]