run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags: []

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Go vet
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Advanced static analysis
    - unused          # Check for unused constants, variables, functions and types
    - gocyclo         # Cyclomatic complexity
    - gofmt           # Check formatting
    - goimports       # Check imports formatting
    - misspell        # Check for misspellings
    - unconvert       # Remove unnecessary type conversions
    - dupl            # Code clone detection
    - goconst         # Find repeated strings that could be constants
    - godot           # Check if comments end in a period
    - exportloopref   # Check for pointers to enclosing loop variables
    - gosec           # Security analyzer
  
  disable:
    - maligned        # Too strict and often not helpful
    - prealloc        # Can be noisy

linters-settings:
  gocyclo:
    min-complexity: 15

  gosec:
    severity: "low"
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

  goimports:
    local-prefixes: craftops

  misspell:
    locale: US

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  staticcheck:
    go: "1.21"

  unused:
    go: "1.21"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo
    
    - path: cmd/
      linters:
        - gocyclo  # Main functions can be a bit complex
    
  exclude:
    # Exclude some lints that are not critical
    - "Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked"
    
severity:
  default-severity: error