run:
  timeout: 5m
  go: "1.23"

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
  
  disable:
    - ineffassign  # Too many false positives
    - godot        # Too strict

linters-settings:
  gosec:
    severity: "medium"
    excludes:
      - G104  # Covered by errcheck

  goimports:
    local-prefixes: craftops

  misspell:
    locale: US

  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    - path: cmd/
      linters:
        - errcheck
    
    # Allow deferred error checks
    - text: "Error return value of .* is not checked"
      source: "defer.*\\."
    
    # Common safe patterns
    - text: "Error return value of.*Print.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Write.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Close.*is not checked"
      linters: [errcheck]
    - text: "Error return value of.*Remove.*is not checked"
      linters: [errcheck]

severity:
  default-severity: error