run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags: []

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck        # Check for unchecked errors (critical)
    - gosimple        # Simplify code
    - govet           # Go vet (critical)
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Advanced static analysis (critical)
    - unused          # Check for unused constants, variables, functions and types
    - gofmt           # Check formatting (critical)
    - goimports       # Check imports formatting
    - misspell        # Check for misspellings
    - gosec           # Security analyzer (critical)
  
  disable:
    - godot           # Too strict about comment periods
    - gocyclo         # Complexity checks can be noisy
    - goconst         # String constants can be noisy
    - dupl            # Code clone detection can be noisy
    - unconvert       # Can be noisy

linters-settings:
  gosec:
    severity: "medium"
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)

  goimports:
    local-prefixes: craftops

  misspell:
    locale: US

  errcheck:
    check-type-assertions: false  # Less strict
    check-blank: false           # Less strict



issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    - path: cmd/
      linters:
        - errcheck  # CLI code often ignores some errors intentionally
    
    # Allow deferred error checks with blank identifier
    - text: "Error return value of .* is not checked"
      source: "defer.*\\."
    
    # Allow blank assignment for error returns in specific cases
    - text: "Error return value of .* is not checked"
      source: ".*_ = .*\\.(Finish|Close|Flush)\\(\\)"
    
  exclude:
    # Common patterns that are usually safe to ignore
    - "Error return value of.*\\.Close.*is not checked"
    - "Error return value of.*\\.Finish.*is not checked"
    - "Error return value of.*printf.*is not checked"

severity:
  default-severity: error