[build-system]
requires = ["setuptools>=69.0.2", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minecraft-mod-manager"
version = "1.0.0"
description = "A comprehensive Minecraft server management tool"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]
dependencies = [
    "aiohttp>=3.9.1",
    "requests>=2.31.0",
    "tqdm>=4.66.1",
    "typing-extensions>=4.9.0"
]

[project.urls]
Homepage = "https://github.com/yourusername/minecraft-mod-manager"
Repository = "https://github.com/yourusername/minecraft-mod-manager.git"
Issues = "https://github.com/yourusername/minecraft-mod-manager/issues"

[project.scripts]
minecraft-mod-manager = "minecraft_mod_manager.__main__:main"

[tool.setuptools]
packages = ["minecraft_mod_manager"]

[tool.setuptools.package-data]
minecraft_mod_manager = ["config.jsonc.example"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["minecraft_mod_manager"]
combine-as-imports = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=minecraft_mod_manager"
testpaths = ["tests"] 