name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: CraftOps version
      placeholder: output of `craftops --version`
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Relevant config (redact secrets)
      render: toml
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: text
