name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: craftops --version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: text
