[minecraft]
version = "1.20.1"
modloader = "fabric"

[paths]
server = "/path/to/minecraft/server"
mods = "/path/to/minecraft/server/mods"
backups = "/path/to/minecraft/backups"
logs = "/path/to/minecraft/logs/mod-manager.log"

[server]
jar = "server.jar"
java_flags = [
    "-Xms4G",
    "-Xmx4G",
    "-XX:+UseG1GC",
    "-XX:+ParallelRefProcEnabled",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:+DisableExplicitGC",
    "-XX:+AlwaysPreTouch"
]
stop_command = "stop"
status_check_interval = 30
max_stop_wait = 300

[backup]
max_mod_backups = 3
mod_backup_dir = "mod_backups"
name_format = "%Y%m%d_%H%M%S"

[notifications]
discord_webhook = ""
warning_template = "Server will restart in {minutes} minutes for updates"
warning_intervals = [15, 10, 5, 1]

[mods]
auto_update = true
backup_before_update = true
notify_before_update = true
update_check_interval = 24
chunk_size = 5
max_retries = 3
base_delay = 2

# Add your mods here
[mods.sources]
modrinth = [
    "https://modrinth.com/mod/fabric-api",
    "https://modrinth.com/mod/lithium",
    "https://modrinth.com/mod/starlight"
]
curseforge = [
    "https://www.curseforge.com/minecraft/mc-mods/jei",
    "https://www.curseforge.com/minecraft/mc-mods/jade"
] 