name: Repository Maintenance

on:
  schedule:
    # Run daily at 2 AM UTC for issue management
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale-management:
    name: Stale Issues & PRs
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issue configuration
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed if no further activity occurs. 
            
            If this issue is still relevant, please add the `keep-open` label or comment to keep it active.
          
          close-issue-message: |
            This issue was automatically closed due to inactivity.
            If you believe this should remain open, please reopen it with updated information.
          
          # Pull request configuration  
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            Please rebase against the latest main branch and address any feedback to keep it active.
          
          close-pr-message: |
            This pull request was automatically closed due to inactivity.
            Feel free to reopen with updated changes if you wish to continue this work.
          
          # Timing configuration
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-close: 14
          
          # Labels
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'keep-open,bug,enhancement,security,urgent'
          exempt-pr-labels: 'keep-open,work-in-progress,urgent'
          
          # Limits
          operations-per-run: 50
          
          # Remove stale label when updated
          remove-stale-when-updated: true
