name: Tests

on:
  workflow_call:
    outputs:
      coverage:
        description: "Test coverage percentage"
        value: ${{ jobs.test.outputs.coverage }}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.percentage }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install pytest pytest-asyncio pytest-cov
        pip install -e .
        
    - name: Create test directories
      run: |
        mkdir -p tests/test_data/server
        mkdir -p tests/test_data/mods
        mkdir -p tests/test_data/backups
        mkdir -p tests/test_data/logs
        
    - name: Lint and fix with Ruff
      run: |
        pip install ruff
        ruff check . --fix
        
    - name: Commit Ruff fixes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style: auto-fixes by Ruff'
        file_pattern: '*.py'
        
    - name: Type check with mypy
      run: |
        mypy minecraft_mod_manager --strict
        
    - name: Test with pytest
      id: coverage
      run: |
        pytest tests/ --cov=minecraft_mod_manager --cov-report=xml --asyncio-mode=auto -v
        echo "percentage=$(coverage report | grep TOTAL | awk '{print $NF}')" >> $GITHUB_OUTPUT
        
    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }} 